### PR TITLE
Update events page with mockups of various notifications

### PR DESCRIPTION
**Pull request by brampitoyo**

### CODE REVIEW

**Comment by muffinresearch** [comment]
Looks like there's some conflicts to resolve.

**Comment by andymckay** [comment]
Sorry bram, I merged your last commit and then fixed up the .rst issues. So its totally my fault. I'm happy to resolve the issues on this commit since I screwed it up.

**Comment by brampitoyo** [comment]
Yes, please. You can fix this issue. Thanks!

**Comment by andymckay** [comment]
Done. https://github.com/mozilla/payments/pull/37, just git pull and you'll get the spanky new version.

**Pull request closed without merging**
