### PR TITLE
Show one card at a time, add edit card flow

### PR DESCRIPTION
**Pull request by brampitoyo**
- Replaced buy flow so it uses a `<select>` box that shows only one
  card at a time, instead of multiple
- Added link to the end of the buy flow to edit credit card/PayPal
- Link name may need to be revised to “delete credit card’
- Instead of presenting the delete UI inside doorhanger, we can also
  link to the management interface, as long as it links directly to the
  relevant page.

### CODE REVIEW

**Comment by kumar303** [comment]
Awesome, I think the 'edit card' at the end makes a lot of sense. The last screen doesn't have an OK button anymore. I think we need that. In addition to closing the window, I was envisioning that would message the third party to update their UI for a "product purchased" state.

**Comment by tofumatt** [comment]
:+1: I dig this; I meant to say so this morning but filed #115 then got distracted.

Good point by @kumar303 about an "okay/done" button at the "finished" screen.

**Comment by brampitoyo** [comment]
I’ve revised the management interface to address some issues. I’ll address #115 separately.

**Comment by kumar303** [comment]
oops, sorry I missed this patch earlier

**Pull request merged**
